apiVersion: v1
kind: Service
metadata:
  name: daps-master-1
spec:
  ports:
    - port: 53575
      name: regtest
    - port: 53573
      name: testnet
    - port: 53572
      name: mainnet
  selector:
    app: daps-master-1
  sessionAffinity: None
  type: LoadBalancer
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: master-1-pv-volume
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 0.1Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: master-1-pv-claim
  hostPath:
    path: "/tmp/pv/master1"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: master-1-pv-claim
  labels:
    app: daps-master-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: daps-master-1
  labels:
    app: daps-master-1
spec:
  selector:
    matchLabels:
      app: daps-master-1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: daps-master-1
      annotations:
        test: test
    spec:
      hostAliases:
      - ip: "10.10.10.2"
        hostnames:
        - "master.1"
      containers:
      - image: r.cfcr.io/hysmagus/hysmagus/daps_min:develop
        imagePullPolicy: Always
        name: dapsd
        ports:
        - containerPort: 53575
          name: regtest
        - containerPort: 53573
          name: testnet
        - containerPort: 53572
          name: mainnet
        volumeMounts:
        - name: master1data
          mountPath: /root/.dapscoin/
        command: ["/bin/bash","-c","dapscoind"]
      volumes:
      - name: master1data
        persistentVolumeClaim:
          claimName: master-1-pv-claim
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: regcred
      
